/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Conexao.Conexao;
import Dao.DaoValores;
import estacionamento1.Valores;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class TelaValores extends javax.swing.JFrame {

    private DaoValores daoValores;
    private Conexao conexao;

    public TelaValores() {

        initComponents();
        daoValores = new DaoValores();

        // Adiciona ouvintes de foco para formatar e arredondar os valores
        addFocusListeners(txt1Hora);
        addFocusListeners(txt2Horas);
        addFocusListeners(txt3Horas);
        addFocusListeners(txt6Horas);
        addFocusListeners(txt12Horas);
        addFocusListeners(txt24Horas);
        addFocusListeners(txtMensal);

        // Carrega os valores do arquivo e define nos campos de texto
        List<Valores> listaValores = daoValores.listaValores();
        if (!listaValores.isEmpty()) {
            setCamposEditaveis(false);
            Valores valores = listaValores.get(0); // Supondo que só haja um conjunto de valores no arquivo
            txt1Hora.setText(String.valueOf(valores.getHora1()));
            txt2Horas.setText(String.valueOf(valores.getHora2()));
            txt3Horas.setText(String.valueOf(valores.getHora3()));
            txt6Horas.setText(String.valueOf(valores.getHora6()));
            txt12Horas.setText(String.valueOf(valores.getHora12()));
            txt24Horas.setText(String.valueOf(valores.getDiaria()));
            txtMensal.setText(String.valueOf(valores.getMensal()));
        }
    }

    private void addFocusListeners(JTextField textField) {
        textField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                // Remove vírgulas e pontos antes de editar
                String text = textField.getText().replaceAll("[,.]", "");
                textField.setText(text);
            }

            @Override
            public void focusLost(FocusEvent e) {
                // Formata o texto para exibir duas casas decimais após o ponto
                try {
                    double value = Double.parseDouble(textField.getText().replace(",", "."));
                    String formattedValue = new DecimalFormat("#0.00", new DecimalFormatSymbols(Locale.US)).format(value);
                    textField.setText(formattedValue);
                } catch (NumberFormatException ex) {
                    // Trata a exceção se a entrada do usuário não for um número válido
                    textField.setText("0.00");
                }
            }
        });
    }

    private void setCamposEditaveis(boolean editaveis) {
        txt1Hora.setEnabled(editaveis);
        txt2Horas.setEnabled(editaveis);
        txt3Horas.setEnabled(editaveis);
        txt6Horas.setEnabled(editaveis);
        txt12Horas.setEnabled(editaveis);
        txt24Horas.setEnabled(editaveis);
        txtMensal.setEnabled(editaveis);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl1Hora = new javax.swing.JLabel();
        lbl2Horas = new javax.swing.JLabel();
        txt3Horas = new javax.swing.JTextField();
        lbl3Horas = new javax.swing.JLabel();
        lbl6Horas = new javax.swing.JLabel();
        txt6Horas = new javax.swing.JTextField();
        txt12Horas = new javax.swing.JTextField();
        lbl12Horas = new javax.swing.JLabel();
        lbl24Horas = new javax.swing.JLabel();
        txt24Horas = new javax.swing.JTextField();
        lblMensal = new javax.swing.JLabel();
        txtMensal = new javax.swing.JTextField();
        btnSalvarValores = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        txt1Hora = new javax.swing.JTextField();
        txt2Horas = new javax.swing.JTextField();
        btnLimpar = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 0, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Valores");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jLabel1)
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lbl1Hora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl1Hora.setLabelFor(txt1Hora);
        lbl1Hora.setText("1 Hora:");
        lbl1Hora.setToolTipText("Insira o valor a ser pago por 1 hora de estacionamento");

        lbl2Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl2Horas.setLabelFor(txt2Horas);
        lbl2Horas.setText("2 Horas:");

        txt3Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt3Horas.setToolTipText("Insira o valor a ser pago por 3 horas de estacionamento");

        lbl3Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl3Horas.setLabelFor(txt3Horas);
        lbl3Horas.setText("3 Horas:");

        lbl6Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl6Horas.setLabelFor(txt6Horas);
        lbl6Horas.setText("6 Horas:");

        txt6Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt6Horas.setToolTipText("Insira o valor a ser pago por 6 horas de estacionamento");

        txt12Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt12Horas.setToolTipText("Insira o valor a ser pago por 12 horas de estacionamento");

        lbl12Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl12Horas.setLabelFor(txt12Horas);
        lbl12Horas.setText("12 Horas:");

        lbl24Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbl24Horas.setLabelFor(txt24Horas);
        lbl24Horas.setText("24 Horas:");

        txt24Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt24Horas.setToolTipText("Insira o valor a ser pago por 24 horas de estacionamento");

        lblMensal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMensal.setLabelFor(txtMensal);
        lblMensal.setText("Mensal:");

        txtMensal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMensal.setToolTipText("Insira o valor a ser pago mensalmente para estacionar o carro");

        btnSalvarValores.setBackground(new java.awt.Color(153, 0, 153));
        btnSalvarValores.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvarValores.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarValores.setText("Salvar");
        btnSalvarValores.setToolTipText("Clique aqui para salvar alterações dos precos vigentes no estacionamento");
        btnSalvarValores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarValoresActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(204, 102, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique aqui para voltar para tela anterior");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txt1Hora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt1Hora.setToolTipText("Insira o valor a ser pago por 1 hora de estacionamento");

        txt2Horas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt2Horas.setToolTipText("Insira o valor a ser pago por 2 horas de estacionamento");

        btnLimpar.setBackground(new java.awt.Color(153, 0, 153));
        btnLimpar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLimpar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpar.setText("Limpar");
        btnLimpar.setToolTipText("Clique aqui para apagar precos vigentes no estacionamento");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl2Horas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl1Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt2Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt1Hora, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(btnSalvarValores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl24Horas)
                                    .addComponent(lblMensal))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt24Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMensal, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl6Horas)
                                    .addComponent(lbl12Horas)
                                    .addComponent(lbl3Horas))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt3Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt12Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt6Horas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnVoltar)
                            .addComponent(btnLimpar)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl1Hora)
                    .addComponent(txt1Hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl2Horas)
                    .addComponent(txt2Horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvarValores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl3Horas)
                            .addComponent(txt3Horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl6Horas)
                            .addComponent(txt6Horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnLimpar))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl12Horas)
                            .addComponent(txt12Horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl24Horas)
                            .addComponent(txt24Horas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMensal)
                            .addComponent(txtMensal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVoltar)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarValoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarValoresActionPerformed
          setCamposEditaveis(false);
    try {
        // Obtenha os valores dos campos de texto
        double hora1 = Double.parseDouble(txt1Hora.getText());
        double hora2 = Double.parseDouble(txt2Horas.getText());
        double hora3 = Double.parseDouble(txt3Horas.getText());
        double hora6 = Double.parseDouble(txt6Horas.getText());
        double hora12 = Double.parseDouble(txt12Horas.getText());
        double diaria = Double.parseDouble(txt24Horas.getText());
        double mensal = Double.parseDouble(txtMensal.getText());

        Valores novosValores = new Valores(hora1, hora2, hora3, hora6, hora12, diaria, mensal);

        List<Valores> listaValores = daoValores.listaValores();

        if (!listaValores.isEmpty()) {
            // Se houver valores salvos, atualize os valores existentes
            Valores valores = listaValores.get(0); // Supondo que só haja um conjunto de valores no arquivo
            daoValores.updateValores( novosValores);
        } else {
            // Se não houver valores salvos, adicione os novos valores
            daoValores.addValores(novosValores);
        }
        JOptionPane.showMessageDialog(this, "Cadastro salvo com sucesso!");

    } catch (NumberFormatException e) {
        // Trate a exceção se a entrada do usuário não for um número válido
        JOptionPane.showMessageDialog(this, "Por favor, insira valores numéricos válidos.");
    }


    }//GEN-LAST:event_btnSalvarValoresActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // Fecha a tela atual
        this.dispose();

        // Abre a tela inicial
        TelaFinanceiro telaFinanceiro = new TelaFinanceiro();
        telaFinanceiro.setVisible(true);

    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // Limpar os campos de texto
        txt1Hora.setText("");
        txt2Horas.setText("");
        txt3Horas.setText("");
        txt6Horas.setText("");
        txt12Horas.setText("");
        txt24Horas.setText("");
        txtMensal.setText("");

        // Torna os campos de texto editáveis
        setCamposEditaveis(true);

    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaValores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaValores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaValores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaValores.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaValores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvarValores;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl12Horas;
    private javax.swing.JLabel lbl1Hora;
    private javax.swing.JLabel lbl24Horas;
    private javax.swing.JLabel lbl2Horas;
    private javax.swing.JLabel lbl3Horas;
    private javax.swing.JLabel lbl6Horas;
    private javax.swing.JLabel lblMensal;
    private javax.swing.JTextField txt12Horas;
    private javax.swing.JTextField txt1Hora;
    private javax.swing.JTextField txt24Horas;
    private javax.swing.JTextField txt2Horas;
    private javax.swing.JTextField txt3Horas;
    private javax.swing.JTextField txt6Horas;
    private javax.swing.JTextField txtMensal;
    // End of variables declaration//GEN-END:variables
}
