/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Conexao.Conexao;
import Dao.DaoDesconto;
import estacionamento1.Desconto;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class TelaDescontosParceiros extends javax.swing.JFrame {

    private DaoDesconto daoDesconto;
    private Conexao conexao;

    public TelaDescontosParceiros() {

        daoDesconto = new DaoDesconto();
        initComponents();
        atualizarComboBoxDescontos();
    }

    private void atualizarComboBoxDescontos() {
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>();
        comboBoxModel.addElement("Selecione o Desconto a ser Excluido");
        List<Desconto> descontoList = daoDesconto.listaDesconto();
        for (Desconto desconto : descontoList) {
            String item = desconto.getNomeDesconto() + " - " + desconto.getDesconto() + "%";
            comboBoxModel.addElement(item);
        }
        ComboBoxDesc.setModel(comboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblNomeDesconto = new javax.swing.JLabel();
        txtNomeDesconto = new javax.swing.JTextField();
        lblDesconto = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        ComboBoxDesc = new javax.swing.JComboBox<>();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCabecalho.setBackground(new java.awt.Color(153, 0, 153));
        pnlCabecalho.setToolTipText("");

        lblCabecalho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCabecalho.setForeground(new java.awt.Color(255, 255, 255));
        lblCabecalho.setText("Descontos Parceiros");

        javax.swing.GroupLayout pnlCabecalhoLayout = new javax.swing.GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap(152, Short.MAX_VALUE)
                .addComponent(lblCabecalho)
                .addGap(116, 116, 116))
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblCabecalho)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblNomeDesconto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeDesconto.setLabelFor(txtNomeDesconto);
        lblNomeDesconto.setText("Nome:");

        txtNomeDesconto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeDesconto.setToolTipText("Insira nome do parceiro que ira gerar o desconto");

        lblDesconto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDesconto.setLabelFor(txtDesconto);
        lblDesconto.setText("Desconto:");

        txtDesconto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDesconto.setToolTipText("Insira o valor do desconto em Porcentagem que será oferecido");

        btnSalvar.setBackground(new java.awt.Color(153, 0, 153));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvar.setText("Salvar");
        btnSalvar.setToolTipText("Clique aqui para salvar novo gerador de desconto");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(204, 102, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique aqui para voltar para pagina anterior");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        ComboBoxDesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel<>(); // Cria um novo modelo de ComboBox
        comboBoxModel.addElement("Selecione o Desconto a ser Excluido"); // Adiciona um item padrão

        // Popula o modelo do ComboBox com os nomes dos parceiros e os descontos correspondentes
        List<Desconto> descontoList = daoDesconto.listaDesconto();
        for (Desconto desconto : descontoList) {
            String item = desconto.getNomeDesconto() + " - " + desconto.getDesconto() + "%";
            comboBoxModel.addElement(item);
        }
        ComboBoxDesc.setModel(comboBoxModel);
        ComboBoxDesc.setToolTipText("Selecione o Desconto a ser Excluido");
        ComboBoxDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxDescActionPerformed(evt);
            }
        });

        btnExcluir.setBackground(new java.awt.Color(255, 0, 0));
        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        btnExcluir.setText("Exlcuir");
        btnExcluir.setToolTipText("Clique aqui para excluir gerador de desconto");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCabecalho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesconto)
                    .addComponent(lblNomeDesconto))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNomeDesconto, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(txtDesconto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalvar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ComboBoxDesc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pnlCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNomeDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNomeDesconto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDesconto)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(btnSalvar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(ComboBoxDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnExcluir)))
                .addGap(30, 30, 30)
                .addComponent(btnVoltar)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void limparCampos() {
        txtNomeDesconto.setText("");
        txtDesconto.setText("");
    }
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // Obtenha os valores dos campos de texto
        String nome = txtNomeDesconto.getText();
        String descontoText = txtDesconto.getText();

        if (nome.isEmpty() && descontoText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha os campos nome e desconto corretamente\n");
            return;
        } else if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha corretamente o nome\n ");
            return;
        } else if (descontoText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha corretamente o desconto\n ");
            return;
        }

        try {
            // Substituir ',' por '.' no campo txtDesconto
            descontoText = descontoText.replace(',', '.');

            // Verificar se o texto contém apenas números e '.' após a substituição
            if (!descontoText.matches("^\\d*\\.?\\d*$")) {
                throw new NumberFormatException();
            }

            double desconto = Double.parseDouble(descontoText);

            // Check if desconto is a non-negative value (you can modify this condition based on your requirements)
            if (desconto < 0) {
                throw new NumberFormatException();
            }

            Desconto novoDesconto = new Desconto(nome, desconto);
            daoDesconto.addDesconto(novoDesconto);
            // Atualizar o texto no campo txtDesconto
            txtDesconto.setText(descontoText);
            JOptionPane.showMessageDialog(this, "Cadastro salvo com sucesso!");
            limparCampos();

            // Atualizar a lista de itens do ComboBox
            atualizarComboBoxDescontos();

            // Adicione a instância à lista de valores (ou faça o que for necessário com esses valores)
            List<Desconto> listaDesconto = Desconto.CadastroDesconto();
            listaDesconto.add(novoDesconto);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Por favor, insira um valor numérico válido.");
        }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
        TelaFinanceiro novaTelaFinanceiro = new TelaFinanceiro();
        novaTelaFinanceiro.setVisible(true);
        limparCampos();

    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
       int selectedIndex = ComboBoxDesc.getSelectedIndex();
        if (selectedIndex != -1) {
            String selectedDesconto = (String) ComboBoxDesc.getSelectedItem();
            String nomeDesconto = selectedDesconto.split(" - ")[0]; // Extrair o nome do desconto

            // Excluir o desconto do DaoDesconto
            daoDesconto.removerDesconto(nomeDesconto);

            // Atualizar a ComboBox após a exclusão
            atualizarComboBoxDescontos();

            // Limpar a seleção da ComboBox
            ComboBoxDesc.setSelectedIndex(-1);
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um desconto para excluir.");
        }
    
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void ComboBoxDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxDescActionPerformed

    }//GEN-LAST:event_ComboBoxDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDescontosParceiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDescontosParceiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDescontosParceiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDescontosParceiros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            new TelaDescontosParceiros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxDesc;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblDesconto;
    private javax.swing.JLabel lblNomeDesconto;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtNomeDesconto;
    // End of variables declaration//GEN-END:variables
}
