/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Dao.DaoCadastroUsuarioSistema;
import estacionamento1.CadastroUsuarioSistema;

import javax.swing.JOptionPane;



public class TelaCadastroUsuarioSistema extends javax.swing.JFrame {

    private DaoCadastroUsuarioSistema daoCadastroUsuarioSistema;

  

    public TelaCadastroUsuarioSistema() {
        initComponents();
        daoCadastroUsuarioSistema = new DaoCadastroUsuarioSistema();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlCabecalho = new javax.swing.JPanel();
        lblCabecalho = new javax.swing.JLabel();
        lblNomeCad = new javax.swing.JLabel();
        txtNomeCad = new javax.swing.JTextField();
        lblCargoCad = new javax.swing.JLabel();
        txtLoginCad = new javax.swing.JTextField();
        lblLoginCad = new javax.swing.JLabel();
        lblSenhaCad = new javax.swing.JLabel();
        btnSalvarCad = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        chkBoxAtendente = new javax.swing.JCheckBox();
        chkBoxGerente = new javax.swing.JCheckBox();
        txtSenhaCad = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlCabecalho.setBackground(new java.awt.Color(153, 0, 153));
        pnlCabecalho.setDoubleBuffered(false);

        lblCabecalho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCabecalho.setForeground(new java.awt.Color(255, 255, 255));
        lblCabecalho.setText("Cadastro");

        javax.swing.GroupLayout pnlCabecalhoLayout = new javax.swing.GroupLayout(pnlCabecalho);
        pnlCabecalho.setLayout(pnlCabecalhoLayout);
        pnlCabecalhoLayout.setHorizontalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCabecalhoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCabecalho)
                .addGap(191, 191, 191))
        );
        pnlCabecalhoLayout.setVerticalGroup(
            pnlCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCabecalhoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblCabecalho)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        lblNomeCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNomeCad.setLabelFor(txtNomeCad);
        lblNomeCad.setText("Nome:");

        txtNomeCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNomeCad.setToolTipText("Insira nome completo do funcionário");
        txtNomeCad.setName(""); // NOI18N

        lblCargoCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCargoCad.setText("Cargo:");

        txtLoginCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLoginCad.setToolTipText("Insira o login designado para este funcionário");

        lblLoginCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLoginCad.setLabelFor(txtLoginCad);
        lblLoginCad.setText("Login:");

        lblSenhaCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenhaCad.setLabelFor(txtSenhaCad);
        lblSenhaCad.setText("Senha:");
        lblSenhaCad.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSalvarCad.setBackground(new java.awt.Color(153, 0, 153));
        btnSalvarCad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSalvarCad.setForeground(new java.awt.Color(255, 255, 255));
        btnSalvarCad.setText("Salvar");
        btnSalvarCad.setToolTipText("Clique aqui para salvar o cadastro");
        btnSalvarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadActionPerformed(evt);
            }
        });

        btnVoltar.setBackground(new java.awt.Color(204, 102, 255));
        btnVoltar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Clique aqui para voltar para tela anerior");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        chkBoxAtendente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBoxAtendente.setText("Atendente");
        chkBoxAtendente.setToolTipText("Selecione caso o cargo seja atendente");
        chkBoxAtendente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBoxAtendenteItemStateChanged(evt);
            }
        });

        chkBoxGerente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chkBoxGerente.setText("Gerente");
        chkBoxGerente.setToolTipText("Selecione caso o cargo seja gerente");
        chkBoxGerente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkBoxGerenteItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomeCad)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnVoltar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvarCad))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblSenhaCad)
                            .addGap(18, 18, 18)
                            .addComponent(txtSenhaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLoginCad)
                        .addGap(23, 23, 23)
                        .addComponent(txtLoginCad, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCargoCad)
                        .addGap(18, 18, 18)
                        .addComponent(chkBoxGerente)
                        .addGap(37, 37, 37)
                        .addComponent(chkBoxAtendente)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(pnlCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeCad)
                    .addComponent(txtNomeCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargoCad)
                    .addComponent(chkBoxAtendente)
                    .addComponent(chkBoxGerente))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoginCad)
                    .addComponent(txtLoginCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSenhaCad)
                        .addGap(0, 7, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtSenhaCad)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(btnSalvarCad))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadActionPerformed
        String nome = txtNomeCad.getText();
        String login = txtLoginCad.getText();
        String senha = txtSenhaCad.getText();
        String cargo = "";

        // Verifica o cargo com base nos checkboxes
        if (chkBoxAtendente.isSelected()) {
            cargo = "Atendente";
        } else if (chkBoxGerente.isSelected()) {
            cargo = "Gerente";
        }

        CadastroUsuarioSistema usuario = new CadastroUsuarioSistema(nome, cargo, login, senha);
        daoCadastroUsuarioSistema.addCadastroUsuarioSistema(usuario);
        JOptionPane.showMessageDialog(this, "Cadastro salvo com sucesso!\n"
                + "Voltando para a página de Login");
        this.dispose();

        // Abre a tela inicial e limpa os campos
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.limparCampos();
        telaInicial.setVisible(true);
        

    }//GEN-LAST:event_btnSalvarCadActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // Fecha a tela atual
        this.dispose();

        // Abre a tela inicial e limpa os campos
        TelaInicial telaInicial = new TelaInicial();
        telaInicial.limparCampos();
        telaInicial.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void chkBoxGerenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBoxGerenteItemStateChanged
        if (chkBoxGerente.isSelected()) {
            chkBoxAtendente.setSelected(false);
        }

    }//GEN-LAST:event_chkBoxGerenteItemStateChanged

    private void chkBoxAtendenteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkBoxAtendenteItemStateChanged
        if (chkBoxAtendente.isSelected()) {
            chkBoxGerente.setSelected(false);
        }
    }//GEN-LAST:event_chkBoxAtendenteItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuarioSistema.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuarioSistema.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuarioSistema.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroUsuarioSistema.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroUsuarioSistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarCad;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JCheckBox chkBoxAtendente;
    private javax.swing.JCheckBox chkBoxGerente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCabecalho;
    private javax.swing.JLabel lblCargoCad;
    private javax.swing.JLabel lblLoginCad;
    private javax.swing.JLabel lblNomeCad;
    private javax.swing.JLabel lblSenhaCad;
    private javax.swing.JPanel pnlCabecalho;
    private javax.swing.JTextField txtLoginCad;
    private javax.swing.JTextField txtNomeCad;
    private javax.swing.JPasswordField txtSenhaCad;
    // End of variables declaration//GEN-END:variables
}
