package Telas;

import Conexao.SenhaCripto;
import estacionamento1.CadastroUsuarioSistema;
import Dao.DaoCadastroUsuarioSistema;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class TelaInicial extends javax.swing.JFrame {

    private final DaoCadastroUsuarioSistema daoCadastroUsuarioSistema;

    public TelaInicial() {
        initComponents();
        daoCadastroUsuarioSistema = new DaoCadastroUsuarioSistema();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PnlRoxoCabecalho = new javax.swing.JPanel();
        lblCabecalhio = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        btnCadastro = new javax.swing.JButton();
        btnEntrar = new javax.swing.JButton();
        txtSenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estacionamento");

        PnlRoxoCabecalho.setBackground(new java.awt.Color(153, 0, 153));
        PnlRoxoCabecalho.setForeground(new java.awt.Color(255, 255, 255));

        lblCabecalhio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCabecalhio.setForeground(new java.awt.Color(255, 255, 255));
        lblCabecalhio.setText("Estacionamento");

        javax.swing.GroupLayout PnlRoxoCabecalhoLayout = new javax.swing.GroupLayout(PnlRoxoCabecalho);
        PnlRoxoCabecalho.setLayout(PnlRoxoCabecalhoLayout);
        PnlRoxoCabecalhoLayout.setHorizontalGroup(
            PnlRoxoCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnlRoxoCabecalhoLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addComponent(lblCabecalhio)
                .addGap(135, 135, 135))
        );
        PnlRoxoCabecalhoLayout.setVerticalGroup(
            PnlRoxoCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnlRoxoCabecalhoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblCabecalhio)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLogin.setLabelFor(txtLogin);
        lblLogin.setText("Login:");
        lblLogin.setToolTipText("");

        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLogin.setToolTipText("Digite seu login de acesso");

        lblSenha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSenha.setLabelFor(txtSenha);
        lblSenha.setText("Senha:");

        btnCadastro.setBackground(new java.awt.Color(204, 102, 255));
        btnCadastro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCadastro.setText("Cadastro");
        btnCadastro.setToolTipText("Clique para cadastrar novo usuário");
        btnCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroActionPerformed(evt);
            }
        });

        btnEntrar.setBackground(new java.awt.Color(153, 0, 153));
        btnEntrar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar.setText("Entrar");
        btnEntrar.setToolTipText("Clique para entrar nas funcionalidades do programa");
        btnEntrar.setAutoscrolls(true);
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlLoginLayout = new javax.swing.GroupLayout(pnlLogin);
        pnlLogin.setLayout(pnlLoginLayout);
        pnlLoginLayout.setHorizontalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addComponent(btnCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlLoginLayout.createSequentialGroup()
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha)
                            .addComponent(lblLogin))
                        .addGap(18, 18, 18)
                        .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(txtSenha))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        pnlLoginLayout.setVerticalGroup(
            pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSenha)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(pnlLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastro)
                    .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PnlRoxoCabecalho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PnlRoxoCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void limparCampos() {
        txtLogin.setText("");
        txtSenha.setText("");
    }
    private void btnCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroActionPerformed
        TelaCadastroUsuarioSistema novaTelaCadastroUsuarioSistema = new TelaCadastroUsuarioSistema();
        novaTelaCadastroUsuarioSistema.setVisible(true);
        this.setVisible(false);
// Substitua a linha acima pela seguinte para garantir a atualização da tabela ao voltar
        novaTelaCadastroUsuarioSistema.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                // Atualize a tabela ao voltar da tela de cadastro

                setVisible(true);
            }
        });
        limparCampos();
    }//GEN-LAST:event_btnCadastroActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
     String login = txtLogin.getText().trim();
    char[] senhaChars = txtSenha.getPassword();
    String senha = new String(senhaChars).trim();
    
    // Criptografa a senha digitada
    String senhaCriptografada = SenhaCripto.senhaCripto(senha);

    if (login.isEmpty() && senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha login e senha corretamente\n ou clique em cadastrar");
        return;
    } else if (login.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha corretamente o login\n ou clique em cadastrar");
        return;
    } else if (senha.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, preencha corretamente a senha\n ou clique em cadastrar");
        return;
    }
    try {
        List<CadastroUsuarioSistema> cadastros = daoCadastroUsuarioSistema.listaCadastroUsuarioSistema();
        boolean usuarioCadastrado = false;

        for (CadastroUsuarioSistema cadastro : cadastros) {
            if (cadastro.getLogin().equals(login) && cadastro.getSenha().equals(senhaCriptografada)) {
                usuarioCadastrado = true;
                abrirTelaCorrespondente(cadastro.getCargo(), this);
                break;
            }
        }

        if (!usuarioCadastrado) {
            exibirTelaCadastro();
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erro ao tentar autenticar o usuário.");
    }

    limparCampos();
}

private void abrirTelaCorrespondente(String cargo, javax.swing.JFrame telaAnterior) {
    switch (cargo) {
        case "Gerente":
            TelaFinanceiro telaFinanceiro = new TelaFinanceiro();
            telaFinanceiro.setVisible(true);
            this.setVisible(false);
            break;
        case "Atendente":
            TelaVeiculo telaVeiculo = new TelaVeiculo(telaAnterior);
            telaVeiculo.setVisible(true);
            this.setVisible(false);
            break;
        default:
            JOptionPane.showMessageDialog(this, "Cargo não reconhecido.");
    }
}

private void exibirTelaCadastro() {
    JOptionPane.showMessageDialog(this, "Usuário não cadastrado. Redirecionando para a página de cadastro.");
    TelaCadastroUsuarioSistema novaTelaCadastroUsuarioSistema = new TelaCadastroUsuarioSistema();
    novaTelaCadastroUsuarioSistema.setVisible(true);
    this.setVisible(false); // Se necessário, esconder a tela de login
    novaTelaCadastroUsuarioSistema.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            setVisible(true);
        }
    });

    }//GEN-LAST:event_btnEntrarActionPerformed

    public JTextField getTxtLogin() {
        return txtLogin;
    }

    public void setTxtLogin(JTextField txtLogin) {
        this.txtLogin = txtLogin;
    }

    public JPasswordField getTxtSenha() {
        return txtSenha;
    }

    public void setTxtSenha(JPasswordField txtSenha) {
        this.txtSenha = txtSenha;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlRoxoCabecalho;
    private javax.swing.JButton btnCadastro;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCabecalhio;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
